### ISSUE TITLE
Does this project need two servers to support it?

### ISSUE THREAD

**Issue by balckapple** [JJLi0427/MQTT_LostFind_wxapp#1]
I found that you are using different MQTT server and database server IPs in your project configuration file, do you need to enable two servers if I want to deploy this, or is there any other easier way
```
{
    "database server":{
        "host":"",
        "port":3306,
        "user":"",
        "password":"",
        "database":""
    },
    "mqtt server":{
        "host":"",
        "port":1883,
        "other_topic":[
            
        ]
    }
}
```

**Comment by JJLi0427** [comment]
You can install the MQTT service and database on the same server, so that the address of the sub-client connection is localhost, and the project can work normally even on one server
